Update deploy-databricks-job.yml

diff --git a/e2e_samples/parking_sensors/devops/templates/jobs/deploy-databricks-job.yml b/e2e_samples/parking_sensors/devops/templates/jobs/deploy-databricks-job.yml
--- a/e2e_samples/parking_sensors/devops/templates/jobs/deploy-databricks-job.yml
+++ b/e2e_samples/parking_sensors/devops/templates/jobs/deploy-databricks-job.yml
@@ -26,10 +26,20 @@ jobs:
           displayName: 'Use Python Version: $(pythonVersion)'
 
         - script: |
-            wget https://github.com/databricks/cli/releases/download/v${databricksCLIVersion}/${databricksFile} -O databricks_cli.zip
-            # Verify the checksum
             tmpdir=$(mktemp -d)
-            unzip databricks_cli.zip -d /usr/local/bin  
+            wget https://github.com/databricks/cli/releases/download/v${databricksCLIVersion}/${databricksFile} -O /$tmpdir/databricks_cli.zip
+            # Verify the checksum
+            cd /$tmpdir
+            sha256sum databricks_cli.zip > /$tmpdir/databricks_cli.zip.sha256
+            sha256sum -c ${FILE}.zip.sha256
+            # Check the exit status of the sha256sum command
+            if [ $? -ne 0 ]; then
+              echo "Checksum validation failed. Exiting."
+              exit 1
+            else
+              echo "Checksum validation succeeded."
+            fi
+            unzip -q /$tmpdir/databricks_cli.zip
             echo "Installed $("databricks" -v)"
           displayName: 'Install Databricks CLI'
         - script: |
